name: Windows Build

on: [ push, pull_request ]

jobs: 
  Windows-Non-POSIX:
    timeout-minutes: 10
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get MSVC Dev Tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - name: Get SDL2 and SDL2_ttf
        run: |
          mkdir temp
          nuget install sdl2.nuget -ExcludeVersion -NonInteractive -OutputDirectory temp\
          nuget install sdl2_ttf.nuget -ExcludeVersion -NonInteractive -OutputDirectory temp\
          robocopy temp\sdl2.nuget\build\native\include\ depends\SDL
          robocopy temp\sdl2_ttf.nuget\build\native\include\ depends\SDL_ttf
          robocopy temp\sdl2.nuget\build\native\lib\x64\dynamic\ depends\SDL
          robocopy temp\sdl2_ttf.nuget\build\native\lib\x64\dynamic\ depends\SDL_ttf
          robocopy temp\sdl2.nuget.redist\build\native\bin\x64\dynamic\ depends\SDL
          robocopy temp\sdl2_ttf.nuget.redist\build\native\bin\x64\dynamic\ depends\SDL_ttf
          if ($LASTEXITCODE -le 7) { exit 0 } else { exit 1 }
      - name: Build
        run: |
          cmake -S . -B builddir -G Ninja
          cmake --build builddir
