name: Linux Build

on: [ push, pull_request ]

jobs: 
  Linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - name: Get System Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential pkg-config
      - name: Build
        run: |
          cmake -S . -B builddir -G Ninja -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-Wall"
          cmake --build builddir

