name: MacOS Build

on: [ push, pull_request ]

jobs: 
  MacOS:
    timeout-minutes: 10
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Get SDL2 and SDL2_ttf
        run: |
          brew install sdl2
          brew install sdl2_ttf
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: builddir

